### ISSUE TITLE
[Bug] TweetWithVisibilityResults not parsed properly

### ISSUE THREAD

**Issue by nullqwertyuiop** [nullqwertyuiop/tweet-crawler#2]
**Describe the bug**
~~Tweet model needs `legacy` data from `TweetDetail` in order to be properly parsed and validated but it is not present in all tweets.~~
Update: `__type: TweetWithVisibilityResults` -> `["tweet"]["legacy"]`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by kaixinol** [comment]
Falling back to traditional web scraping may help.
xpath reference: https://github.com/kaixinol/offline-twitter-cyber-fortune-teller-py/blob/1b6d0535e0ec9df9c8a8110b26444b8201c5a035/config/xpath.toml#L12-L19

**Comment by nullqwertyuiop** [comment]
> Falling back to traditional web scraping may help. xpath reference: https://github.com/kaixinol/offline-twitter-cyber-fortune-teller-py/blob/1b6d0535e0ec9df9c8a8110b26444b8201c5a035/config/xpath.toml#L12-L19

That's what we called *reinventing the wheels*.
